### ISSUE TITLE
dependency on 'vel' data

### ISSUE THREAD

**Issue by cbrown5** [JorGarMol/VoCC#4]
There is a call to the 'vel' data frame but it doesn't exist in the function's definition. 
See the last line:
'CRS(proj4string(vel)))'

So I suggest specifying the projection as an argument to the function (and assume lon lat default)
But you could also have 'vel' as an argument

**Comment by cbrown5** [comment]
Sorry the above refers to the "trajLine()" function

**Comment by JorGarMol** [comment]
Thanks for picking that Chris. I have edited the function to add a CRS argument as suggested.
